[[redirects]]
  from = "/"
  to = "/login/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/dashboard/admin"
  to = "/dashboard/admin.html"
  status = 200

[[redirects]]
  from = "/dashboard/employee"
  to = "/dashboard/employee.html"
  status = 200
